### PR TITLE
Multiple panda robot

### PR DESCRIPTION
**Pull request by meinczingerm**
This PR contains changes necessary to add and control multiple Panda robots in the same env. I added a separate example.py where there is an example of how to add multiple robots and an example env+task to test the double panda arms. The example.py is only added for easy testing, but shouldn't be merged. It might make sense to add DoublePandaArm example into documentation, or somewhere else?

### CODE REVIEW

**Comment by meinczingerm** [comment]
IMO the checks are only failing because of the example.py that should be removed anyway.

**Comment by qgallouedec** [comment]
Can you check the "Allow edits from maintainers" box?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by meinczingerm** [comment]
It is turned on. 
image

**Comment by qgallouedec** [comment]
Any update?

**Comment by meinczingerm** [comment]
It seems, that this is only a conflict because of the coverage. The example.py could be removed if you don't want to have something similar somewhere.

**Comment by qgallouedec** [comment]
I made some comments on your changes, about typos and such, can you take a look?

**Comment by mechtach714** [comment]
Good day, 

Did you guys manage to get a second Franka added to the simulation? I'm trying to simulate object handover between two Franka arms and it would be wonderful if it would be a simple fix to include a second arm.

**Pull request closed without merging**
